# Generated by Django 3.0.5 on 2020-04-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
